#!/usr/bin/env bash
# ami_failure_notify.sh - generic failure notifier invoked from systemd OnFailure=
#
# Usage: ami_failure_notify.sh <failed-unit-name>
#
# Composes a plain-text email summarizing the failure (hostname, unit, exit
# state, last 50 journal lines) and ships it via `himalaya message send` using
# the polymarket account (independentailabs@gmail.com Gmail SMTP).
#
# Exit codes:
#   0  - email sent (or WORKSPACE_FAILURE_NOTIFY_DRY_RUN=1 honored)
#   2  - bad invocation
#   3  - himalaya not on PATH
#   4  - himalaya send failed (this is intentionally non-zero so the failure
#        of the notifier itself is visible in journalctl -u
#        ami-failure-notify@*.service)
#
# Bounded: caller wraps in TimeoutStartSec=5min in the unit. We additionally
# `timeout 60s` the himalaya call so a hung SMTP doesn't pin the unit.

set -euo pipefail

readonly TO_ADDR="${WORKSPACE_FAILURE_NOTIFY_TO:-independentailabs@gmail.com}"
readonly FROM_ADDR="${WORKSPACE_FAILURE_NOTIFY_FROM:-independentailabs@gmail.com}"
readonly HIMALAYA_ACCOUNT="${WORKSPACE_FAILURE_NOTIFY_ACCOUNT:-polymarket}"
# Resolve binary + config relative to $HOME so the script is portable across
# operator workstations (no hardcoded user prefix). Override with
# WORKSPACE_HIMALAYA_BIN / WORKSPACE_HIMALAYA_CONFIG if needed.
readonly HIMALAYA_BIN="${WORKSPACE_HIMALAYA_BIN:-${HOME}/WORKSPACE-VM/.boot-linux/bin/himalaya}"
readonly HIMALAYA_CONFIG="${WORKSPACE_HIMALAYA_CONFIG:-${XDG_CONFIG_HOME:-${HOME}/.config}/himalaya/config.toml}"

log() {
    # Tag every log line with a recognizable prefix so journalctl filtering
    # on the notifier instance is greppable.
    printf '[ami-failure-notify] %s\n' "$*" >&2
}

die() {
    local code="$1"; shift
    log "ERROR: $*"
    exit "$code"
}

if [[ $# -ne 1 ]] || [[ -z "${1:-}" ]]; then
    die 2 "usage: $0 <failed-unit-name>"
fi

readonly FAILED_UNIT="$1"
readonly HOSTNAME_SHORT="$(hostname --short 2>&1 || hostname)"

log "notifier invoked for unit=${FAILED_UNIT} host=${HOSTNAME_SHORT}"

# Pull systemd state. We deliberately do NOT swallow rc here - failing
# `systemctl show` is treated as fatal. In practice it never fails for an
# existing unit; if the unit doesn't exist we WANT to know.
log "fetching systemd state for ${FAILED_UNIT}"
unit_state="$(systemctl --user show "${FAILED_UNIT}" \
    --property=Result,ExecMainStatus,ActiveEnterTimestamp,InactiveEnterTimestamp,SubState,ActiveState)"
log "systemd state captured (${#unit_state} bytes)"

# Extract Result for the subject line. Pure string-extraction pipe; under
# `set -o pipefail` any rc!=0 from sed/head propagates and the script aborts.
result_value=""
while IFS= read -r line; do
    if [[ "${line}" == Result=* ]]; then
        result_value="${line#Result=}"
        break
    fi
done <<<"${unit_state}"
if [[ -z "${result_value}" ]]; then
    result_value="unknown"
fi

# Pull the last 50 journal lines for the failed unit. --no-pager to avoid
# blocking on a TTY pager. -n 50 bounds the volume so the email body stays
# small enough for SMTP. We do NOT swallow errors here; if journalctl
# breaks, we want the notifier to break loudly.
log "fetching last 50 journal lines for ${FAILED_UNIT}"
journal_tail="$(journalctl --user -u "${FAILED_UNIT}" -n 50 --no-pager 2>&1)"
log "journal tail captured (${#journal_tail} bytes)"

readonly SUBJECT="[AMI ALERT] ${HOSTNAME_SHORT}:${FAILED_UNIT} - ${result_value}"

# Build the RFC 5322 message. himalaya `message send` consumes a raw
# message on stdin, headers + blank line + body.
message="$(cat <<EOF
From: ${FROM_ADDR}
To: ${TO_ADDR}
Subject: ${SUBJECT}
Content-Type: text/plain; charset=utf-8

AMI failure-notifier triggered.

  host: ${HOSTNAME_SHORT}
  unit: ${FAILED_UNIT}
  result: ${result_value}
  timestamp: $(date -u +'%Y-%m-%dT%H:%M:%SZ')

----- systemctl show -----
${unit_state}

----- journalctl -u ${FAILED_UNIT} -n 50 -----
${journal_tail}

--
This message was generated by ami-failure-notify@${FAILED_UNIT}.service.
Investigate with: journalctl --user -u ${FAILED_UNIT} -n 200 --no-pager
EOF
)"

# Dry-run mode: log what would have been sent and exit 0. Used by the
# ami-failure-notify-test.service verification step so we don't actually
# blast operator inboxes during sanity tests.
if [[ "${WORKSPACE_FAILURE_NOTIFY_DRY_RUN:-0}" == "1" ]]; then
    log "DRY_RUN=1 - not invoking himalaya. would-send subject: ${SUBJECT}"
    log "DRY_RUN=1 - would-send body length: ${#message} bytes"
    log "DRY_RUN=1 - to=${TO_ADDR} from=${FROM_ADDR} account=${HIMALAYA_ACCOUNT}"
    exit 0
fi

if [[ ! -x "${HIMALAYA_BIN}" ]]; then
    # Fall back to PATH lookup before giving up.
    if ! command -v himalaya ; then
        die 3 "himalaya binary not found at ${HIMALAYA_BIN} or on PATH"
    fi
fi

log "invoking himalaya to send notification (subject: ${SUBJECT})"

# 60s hard timeout on the himalaya invocation. If SMTP hangs we want a
# clean non-zero exit, not a stuck oneshot.
send_rc=0
printf '%s' "${message}" | timeout 60s \
    "${HIMALAYA_BIN}" \
        --config "${HIMALAYA_CONFIG}" \
        --account "${HIMALAYA_ACCOUNT}" \
        message send \
    || send_rc=$?

if [[ "${send_rc}" -ne 0 ]]; then
    die 4 "himalaya send failed (rc=${send_rc}) for unit=${FAILED_UNIT}"
fi

log "notification sent OK for unit=${FAILED_UNIT}"
exit 0
